version: '3'

services:
    chat:
        image: node
        working_dir: /home/node/app
        environment:
            - NODE_ENV=production
        volumes:
            - ../:/home/node/app
        ports:
            - "3000:3000"
        command: "npm start"
    mongo:
        image: mongo
        environment:
            MONGO_INITDB_ROOT_USERNAME: root
            MONGO_INITDB_ROOT_PASSWORD: CVx9AxxCZwkx
    mongo-express:
        image: mongo-express
        ports:
            - "8081:8081"
        environment:
            ME_CONFIG_MONGODB_ADMINUSERNAME: root
            ME_CONFIG_MONGODB_ADMINPASSWORD: CVx9AxxCZwkx