version: '3'

services:
    chat:
        image: node
        container_name: chat-server
        working_dir: /home/node/app
        environment:
            - NODE_ENV=production
        volumes:
            - ../:/home/node/app
        ports:
            - "3000:3000"
        command: "npm start"
        depends_on:
            - mongo
    mongo:
        image: mongo
        container_name: chat-mongo
        environment:
            MONGO_INITDB_ROOT_USERNAME: root
            MONGO_INITDB_ROOT_PASSWORD: bDhtK2zNgLfqrrC2HlWFmzqQT7G99KNl
            MONGO_INITDB_DATABASE: setup
        volumes:
            - ./mongo/setup.js:/docker-entrypoint-initdb.d/setup.js
            - mongo_db-data:/data/db
    mongo-express:
        image: mongo-express
        container_name: chat-mongo-express
        ports:
            - "8081:8081"
        environment:
            ME_CONFIG_MONGODB_ADMINUSERNAME: root
            ME_CONFIG_MONGODB_ADMINPASSWORD: bDhtK2zNgLfqrrC2HlWFmzqQT7G99KNl
        depends_on:
            - mongo

volumes:
    mongo_db-data: